#!/usr/bin/env bash

GODEL_CONFIG="$(dirname $(realpath $0))/godel.config"

################################################################################
# Utilities                                                                    #
################################################################################
printMessage() {
    echo
    echo $@
}

printError() {
    printMessage $@
    printMessage "Run 'help' for more information"
    exit 1
}

checkSudo() {
    if [ `whoami` != root ]; then
        printError "Please run this script using sudo"
    fi
}

checkNoSudo() {
    if [ `whoami` = root ]; then
        printError "Please do not run this script using sudo"
    fi
}

checkConfiguration() {
    if [ -f $GODEL_CONFIG ] && [ -s $GODEL_CONFIG ]; then
        source $GODEL_CONFIG
    else
        printError "Please configure before use"
    fi
}

cleanConfiguration() {
    > $GODEL_CONFIG
}

writeConfigurationValue() {
    echo "$1='${!1}'" >> $GODEL_CONFIG
}

################################################################################
# Configure CLI tool                                                           #
################################################################################
configure() {
    checkSudo
    cleanConfiguration
    printMessage "Configuring GTE tools ..."
    read -p "Ented VPN address: " GODEL_VPN_ADDRESS
    writeConfigurationValue GODEL_VPN_ADDRESS
    read -p "Ented VPN username: " GODEL_VPN_USERNAME
    writeConfigurationValue GODEL_VPN_USERNAME
    read -p "Ented OP secret name: " GODEL_OP_SECRET_NAME
    writeConfigurationValue GODEL_OP_SECRET_NAME
    
    exit $?
}

################################################################################
# Get password                                                                 #
################################################################################
getPassword() {
    checkNoSudo
    checkConfiguration
    printMessage "Getting GTE password ..."
    export OP_SESSION_my=$(op signin my --raw)
    op get item "$GODEL_OP_SECRET_NAME" --fields password | pbcopy
    printMessage "Your password has been copied to the clipboard (Command(⌘) + V for use)"
    
    exit $?
}

################################################################################
# Connect to Godel VPN                                                         #
################################################################################
connectToVPN() {
    checkSudo
    checkConfiguration
    printMessage "Connecting to $GODEL_VPN_ADDRESS ..."
    openconnect $GODEL_VPN_ADDRESS -q -u $GODEL_VPN_USERNAME
    printMessage "You are disconnected from $GODEL_VPN_ADDRESS"
    
    exit $?
}

################################################################################
# Display Help                                                                 #
################################################################################
printHelp() {
    echo "
Commandline tools for Godel VPN [version 1.1]

Usage:  godel <command>

Commands:
  configure       Setup GTE tools;                     [with sudo]
  password        Copy Godel password to clipboard;    [without sudo]
  connect         Connect to Godel VPN;                [with sudo]

Depends on:
  op              Command-line helper for the 1Password password manager;
  pbcopy          Provide copying to the clipboard from command line;
  openconnect     Open client for Cisco AnyConnect VPN;
    "
}

################################################################################
# Main program                                                                 #
################################################################################
case ${1} in
    "configure")
        configure
    ;;
    "password")
        getPassword
    ;;
    "connect")
        connectToVPN
    ;;
    "help")
        printHelp
    ;;
    *)
        printError "Invalid command specified"
    ;;
esac